#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(here)
  library(R.utils)
  library(ggplot2)
  library(cowplot)
})

args <- R.utils::commandArgs(asValue = TRUE)

## ---------------------------
## Parse args
## ---------------------------
alpha_x <- if (is.null(args$alpha_x)) stop("Provide alpha_x=") else as.numeric(args$alpha_x)
alpha_y <- if (is.null(args$alpha_y)) stop("Provide alpha_y=") else as.numeric(args$alpha_y)
alpha_z <- if (is.null(args$alpha_z)) stop("Provide alpha_z=") else as.numeric(args$alpha_z)

label <- if (is.null(args$label)) "run" else as.character(args$label)
edges_flag <- if (is.null(args$show_edges)) FALSE else as.logical(as.integer(args$show_edges))

## ---------------------------
## Paths
## ---------------------------
data_path <- here("application_brain", "consensus_scale33_tau50.RData")
proc_path <- here("application_brain", "results", "processed",
                  "brain_xyz_processed_results.rds")

outDir <- here("application_brain", "figures",
               sprintf("%s_ax%0.2f_ay%0.2f_az%0.2f", label, alpha_x, alpha_y, alpha_z))
dir.create(outDir, recursive = TRUE, showWarnings = FALSE)

cat("Posterior plotting:\n")
cat("  alpha_x =", alpha_x, "\n")
cat("  alpha_y =", alpha_y, "\n")
cat("  alpha_z =", alpha_z, "\n")
cat("  label   =", label, "\n")
cat("  outDir  =", outDir, "\n")
cat("  show_edges =", edges_flag, "\n\n")

## ---------------------------
## Load utility plotting function
## ---------------------------
source(here("R_utilties", "plottingFunctions.R"))

## ---------------------------
## Load processed results
## ---------------------------
res_app <- readRDS(proc_path)

find_tag_by_alpha <- function(obj, ax, ay, az, tol = 1e-8) {
  a_mat <- t(sapply(obj$results, function(r) r$alpha[1:3]))
  idx <- which(abs(a_mat[,1]-ax) < tol & abs(a_mat[,2]-ay) < tol & abs(a_mat[,3]-az) < tol)
  if (length(idx) == 0) stop(sprintf("No run found for alpha=(%.2f,%.2f,%.2f).", ax, ay, az))
  names(obj$results)[idx[1]]
}

tag <- find_tag_by_alpha(res_app, alpha_x, alpha_y, alpha_z)
rr  <- res_app$results[[tag]]

psm_mat <- rr$psm
z_hat   <- as.integer(rr$z_hat)
K_hat   <- rr$K_hat

cat("Matched tag:", tag, "\n")
cat("K_hat =", K_hat, "\n\n")

## ---------------------------
## Load data + drop isolates (must match fitting)
## ---------------------------
load(data_path)  # A_bin_tau, coords
diag(A_bin_tau) <- 0
deg  <- rowSums(A_bin_tau)
keep <- deg > 0

A <- A_bin_tau[keep, keep, drop = FALSE]
diag(A) <- 0
coords_kept <- coords[keep, , drop = FALSE]

stopifnot(nrow(A) == length(z_hat))

## ---------------------------
## Fixed ordering: Left → Right → Other (Brain-Stem)
## ---------------------------
hemi <- ifelse(grepl("^lh\\.", coords_kept$node), "Left",
        ifelse(grepl("^rh\\.", coords_kept$node), "Right",
        ifelse(grepl("^Left-",  coords_kept$node), "Left",
        ifelse(grepl("^Right-", coords_kept$node), "Right", "Other"))))

ord_fixed <- order(factor(hemi, levels = c("Left", "Right", "Other")),
                   coords_kept$node)

A_ord   <- A[ord_fixed, ord_fixed, drop = FALSE]
psm_ord <- psm_mat[ord_fixed, ord_fixed, drop = FALSE]
z_ord   <- z_hat[ord_fixed]
hemi_ord <- hemi[ord_fixed]

## annotation: hemisphere + estimated clustering (optional second column)
ann_df <- data.frame(
  hemisphere = factor(hemi_ord, levels = c("Left", "Right", "Other")),
  est        = factor(z_ord)
)

ann_colors <- list(
  hemisphere = c(Left = "#0072B2", Right = "#D55E00", Other = "#999999")
  # est colors will be auto-generated by plot_psm_with_annotations()
)


## ---------------------------
## Save adjacency (ordered; show hemisphere bar only)
## ---------------------------
title_adj <- sprintf("Adjacency (Left–Right order), alpha=(%.2f,%.2f,%.2f)",
                     alpha_x, alpha_y, alpha_z)

plot_matrix_with_annotations(
  M          = A_ord,
  type       = "adj",
  ann_df     = data.frame(
    hemisphere = factor(hemi_ord, levels = c("Left","Right","Other")),
    est        = factor(z_ord)
  ),
  show_cols  = c("hemisphere", "est"),
  ann_colors = list(
    hemisphere = c(Left = "#0072B2", Right = "#D55E00", Other = "#999999")
    # est colors auto-generated
  ),
  gaps_by    = hemi_ord,  # hemisphere separation (use z_ord if you prefer cluster gaps)
  main = title_adj,
  filename   = file.path(outDir, "adjacency_left_right_order.pdf")
)


## ---------------------------
## Save PSM
## ---------------------------
# PSM-based dissimilarity
D_psm <- 1 - psm_mat
diag(D_psm) <- 0

hc_psm <- hclust(as.dist(D_psm), method = "average")
ord_psm <- hc_psm$order

psm_ord  <- psm_mat[ord_psm, ord_psm, drop = FALSE]
A_ord2   <- A[ord_psm, ord_psm, drop = FALSE]      # optional if you want adjacency in same order
z_ord    <- z_hat[ord_psm]
hemi_ord <- hemi[ord_psm]

title_psm <- sprintf("PSM, alpha=(%.2f,%.2f,%.2f), K_hat=%d",
                     alpha_x, alpha_y, alpha_z, K_hat)

plot_matrix_with_annotations(
  M          = psm_ord,
  type       = "psm",
  mat_palette = "Blues",
  n_mat_cols  = 120,
  ann_df     = data.frame(
    hemisphere = factor(hemi_ord, levels = c("Left","Right","Other")),
    est        = factor(z_ord)
  ),
  show_cols  = c("hemisphere", "est"),
  ann_colors = list(
    hemisphere = c(Left = "#0072B2", Right = "#D55E00", Other = "#999999")
  ),
  gaps_by    = z_ord,   # or hemi_ord if you want hemisphere gaps
  main = title_psm,
  filename   = file.path(outDir, "psm_psmOrder.pdf")
)

## ---------------------------
## 3-view cluster plot helper
## ---------------------------
# Edge list for optional edges in 3-view plot (in original kept-node order)
edges <- which(A == 1, arr.ind = TRUE)
edges <- edges[edges[, 1] < edges[, 2], , drop = FALSE]

edges_df <- data.frame(
  x1 = coords_kept$x[edges[, 1]],
  y1 = coords_kept$y[edges[, 1]],
  z1 = coords_kept$z[edges[, 1]],
  x2 = coords_kept$x[edges[, 2]],
  y2 = coords_kept$y[edges[, 2]],
  z2 = coords_kept$z[edges[, 2]]
)

make_view_plot <- function(nodes_df, edges_df, view = c("xy","xz","yz"),
                           show_edges = TRUE,
                           edge_alpha = 0.06, edge_lwd = 0.25,
                           node_alpha = 0.95, node_size = 2.0) {

  view <- match.arg(view)

  if (view == "xy") {
    xvar <- "x"; yvar <- "y"
    ex1 <- "x1"; ey1 <- "y1"; ex2 <- "x2"; ey2 <- "y2"
    ttl <- "Axial (x–y)"
  } else if (view == "xz") {
    xvar <- "x"; yvar <- "z"
    ex1 <- "x1"; ey1 <- "z1"; ex2 <- "x2"; ey2 <- "z2"
    ttl <- "Coronal (x–z)"
  } else {
    xvar <- "y"; yvar <- "z"
    ex1 <- "y1"; ey1 <- "z1"; ex2 <- "y2"; ey2 <- "z2"
    ttl <- "Sagittal (y–z)"
  }

  p <- ggplot()

  if (show_edges && nrow(edges_df) > 0) {
    p <- p + geom_segment(
      data = edges_df,
      aes(x = .data[[ex1]], y = .data[[ey1]], xend = .data[[ex2]], yend = .data[[ey2]]),
      alpha = edge_alpha,
      linewidth = edge_lwd
    )
  }

  p +
    geom_point(
      data = nodes_df,
      aes(x = .data[[xvar]], y = .data[[yvar]], color = cluster),
      alpha = node_alpha,
      size = node_size
    ) +
    coord_equal() +
    theme_minimal(base_size = 12) +
    labs(title = ttl, x = xvar, y = yvar, color = "Cluster") +
    theme(plot.title = element_text(face = "bold"),
          panel.grid.minor = element_blank())
}

## ---------------------------
## Save 3-view cluster plot (kept-node geometry; colored by z_hat)
## ---------------------------
nodes_df <- coords_kept
nodes_df$cluster <- factor(z_hat)

p_xy <- make_view_plot(nodes_df, edges_df, "xy", show_edges = edges_flag)
p_xz <- make_view_plot(nodes_df, edges_df, "xz", show_edges = edges_flag)
p_yz <- make_view_plot(nodes_df, edges_df, "yz", show_edges = edges_flag)

p_views <- cowplot::plot_grid(p_xy, p_xz, p_yz, nrow = 1)
title_cl <- sprintf("VI clusters, alpha=(%.2f,%.2f,%.2f), K_hat=%d",
                    alpha_x, alpha_y, alpha_z, K_hat)

p_views <- cowplot::ggdraw(p_views) +
  cowplot::draw_label(title_cl, x = 0.01, y = 0.98, hjust = 0, vjust = 1,
                      fontface = "bold", size = 14)

ggsave(file.path(outDir, "clusters_3views.pdf"),
       p_views, width = 12, height = 4, dpi = 300)

## ---------------------------
## Save metadata
## ---------------------------
writeLines(c(
  sprintf("tag: %s", tag),
  sprintf("alpha_x: %.4f", alpha_x),
  sprintf("alpha_y: %.4f", alpha_y),
  sprintf("alpha_z: %.4f", alpha_z),
  sprintf("K_hat: %d", K_hat),
  sprintf("show_edges: %s", edges_flag),
  "order: Left -> Right -> Other (by node name)"
), con = file.path(outDir, "run_info.txt"))

cat("Saved plots to:\n  ", outDir, "\n")